apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: frontend
      port: {{ .Values.frontendPort }}
      targetPort: {{ .Values.frontendTargetPort }}
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: backend
      port: {{ .Values.backendPort }}
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - name: db
      port: {{ .Values.dbPort }}
  selector:
    app: db
  type: ClusterIP